@startuml

title CI/CD Workflow

actor "Developer"
entity "Github"

entity "CircleCI"
actor "Reviewer"
entity "AWS ECS"
entity "AWS ECR"
entity "ExApp Lambda"

group Development
    "Developer" <-- "Github": Create branch from master
    "Developer" <- "Developer": Make changes to the code
    "Developer" --> "Github": Push branch
    "Github" -> "Github": Run tests with Github Actions
end
group Review
    "Developer" --> "Github": Create pull request
    "Github" --> "CircleCI": Start build
    "CircleCI" -> "CircleCI": Build, test and create docker images
    "CircleCI" -> "AWS ECR": Push image
    "CircleCI" -> "AWS ECS": Deploy preview
    "CircleCI" -> "Application": Wait for deployed preview
    "CircleCI" -> "ExApp Lambda": Create comment with preview URL
    "ExApp Lambda" -> "Github": Create comment
    "Github" -> "Reviewer": Pull request ready for review
    "Reviewer" -> "Reviewer": Review code
end

alt Pull requests accepted and merged
    "Reviewer" -> "Github" : Merge pull request
    "CircleCI" -> "ExApp Lambda": Get merged preview environment
    "CircleCI" -> "AWS ECS": Delete preview environment
    "Github" --> "CircleCI": Start master build
    "CircleCI" -> "CircleCI": Build, test and create docker images
    "CircleCI" -> "AWS ECR": Push image
    "CircleCI" -> "Application": Deploy to production
    "CircleCI" -> "ExApp Lambda": Trigger delete of unused images
    "ExApp Lambda" -> "AWS ECS": Query for used images
    "ExApp Lambda" -> "AWS ECR": Delete unused images
end
@enduml